### ISSUE TITLE
Possible typo: `RATELIMIT_STORAGE_URL` vs `RATELIMIT_STORAGE_URI`

### ISSUE THREAD

**Issue by lindhe** [inveniosoftware/helm-invenio#139]
The Helm chart sets `INVENIO_RATELIMIT_STORAGE_URL`:

https://github.com/inveniosoftware/helm-invenio/blob/473243a655a6cb27a33ba9db513a70fb6fee99d0/charts/invenio/templates/invenio-configmap.yaml#L12

But it seems like invenio-app-rdm uses `RATELIMIT_STORAGE_URI`:

https://github.com/inveniosoftware/invenio-app-rdm/blob/8130283e9a97b8da32eb754bf277f0d9d3367791/invenio_app_rdm/config.py#L217

Which one is right? Are both right? Do we have a typo?

**Comment by egabancho** [comment]
It's a name change, https://github.com/inveniosoftware/invenio-app/blob/master/invenio_app/ext.py#L114. We should use `RATELIMIT_STORAGE_URI` instead.
