### ISSUE TITLE
worker not starting with celery < 5

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#16]
the problem comes from https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/application.yaml#L204 in the same fashion https://github.com/inveniosoftware/invenio-cli/pull/161/files

**Comment by cfgamboa** [comment]
This is not fixed yet it also affects 
 https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/application.yaml#L244

**Comment by ppanero** [comment]
Invenio has pinned `invenio-celery>=1.2.3` therefore nothing below *celery v5* is allowed.
