### ISSUE TITLE
add mail settings to invenio config

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#45]
INVENIO_MAIL_NOTIFY_SENDER: InvenioRDM <info@inveniordm.com>
  INVENIO_MAIL_SUPPRESS_SEND: 'False'
  INVENIO_MAIL_SERVER: server.com

**Comment by ntarocco** [comment]
done, but now removed with https://github.com/inveniosoftware/helm-invenio/pull/59
