### ISSUE TITLE
 add robots.txt nginx rule

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/helm-invenio#47]
We need to a rewrite rule e.g
```
location /robots.txt {
    alias /opt/invenio/var/instance/static/robots.txt;
    autoindex off;
  }
```
in
- [x] cookiecuter-invenio-rdm docker nginx config
- [x] demo-inveniordm docker nginx config
- [x] zenodo-rdm docker nginx config
- [x] who docker nginx config
- [x] oais docker nginx config
- [x] helm charts nginx config
- [x] Update demo-inveniordm openshift nginx config
- [x] Update zenodo-rdm openshift nginx config

**Comment by alejandromumo** [comment]
Besides repositories, the following openshift configurations were updated:

- `who-rdm` ([url](https://who-rdm.web.cern.ch/robots.txt))
- `cds-rdm-sandbox` ([url](https://sandbox-cds-rdm.web.cern.ch/robots.txt))
- `zenodo-rdm` ([url](https://zenodo-rdm.web.cern.ch/robots.txt))
- `inveniordm-prod` ([url](https://inveniordm.web.cern.ch/robots.txt))
- `inveniordm-qa` ([url](https://inveniordm-qa.web.cern.ch/robots.txt))

Note: the only `robots.txt` that is **currently** being served is in `sandbox-cds-rdm`. Other deployments need to be updated to contain the file in the static folder
