### ISSUE TITLE
The web pod probes time out

### ISSUE THREAD

**Issue by avivace** [inveniosoftware/helm-invenio#52]
I'm still not sure why but with a default deployment from this repository (using managed DBoD and OS from CERN) the web pod gets killed after the probes keep timing out. Simply removing the liveness one semms to fix it.

https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/deployments/web.yaml#L93

`/bin/bash -c "uwsgi_curl $(hostname):5000 /ping -H 'Host: <HOST>"`

**Comment by wgresshoff** [comment]
A colleague explained it to me: the hostname from Values.host is set to a name, that is known outside the cluster. Inside the cluster the K8s DNS is used to resolve the hostname, but that doesn't know it.

**Comment by Samk13** [comment]
closing this and focusing efforts on #104 for efficiency. see [Discord](https://discord.com/channels/692989811736182844/1179090710402715770/1206881869887705098)
