### ISSUE TITLE
INVENIO_DATACITE_ENABLED is "false" instead of "False" leading to a bad python evaluation

### ISSUE THREAD

**Issue by avivace** [inveniosoftware/helm-invenio#53]
We are using `.Values.invenio.datacite.enabled` both as a flag (e.g. to decide when to inject the datacite credentials) and as the value to be injected as `INVENIO_DATACITE_ENABLED` in the [invenio config map](https://github.com/inveniosoftware/helm-invenio/blob/master/invenio/templates/configurations/invenio.yaml#L13) (which feeds the environment). 
However, YAML's boolean `false` gets evaluated to true in python, leading to a messed up configuration (e.g. try to deploy the helm charts with the default values, datacite comes up as enabled because `INVENIO_DATACITE_ENABLED` is set as `false` and not `False` in the configMap).

**Comment by avivace** [comment]
Currently waiting for some feedback - should this be escalated to invenio-config and how we parse invenio.cfg?

**Comment by kpsherva** [comment]
could it be because of the quote marks around the value? it gets evaluated as string and then as true. Did you test without the quotes?
