### ISSUE TITLE
configure mail options

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/helm-invenio#58]
at the moment we have `INVENIO_MAIL_NOTIFY_SENDER` that seems not enough to set the correct email for notification e.g when signup (e.g. zenodo-rdm-qa sends from info@inveniosoftware.org).

- [x] Find the proper configuration to set the email sender. There are many other related variables in app-rdm: https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py
and in Flask-Mail https://pythonhosted.org/Flask-Mail/#configuring-flask-mail

**Comment by ntarocco** [comment]
The register_user should use [SECURITY_EMAIL_SENDER](https://pythonhosted.org/Flask-Security/configuration.html) or default to `MAIL_DEFAULT_SENDER`.

**Comment by ppanero** [comment]
Missing tasks:
- [ ] Remove `SECURITY_EMAIL_SENDER` from `invenio-app-rdm`, change by `MAIL_DEFAULT_SENDER`.
- [ ] Apply changes to `demo-inveniordm-openshift`

**Comment by ppanero** [comment]
@ntarocco I did not find any usage of `SECURITY_EMAIL_SENDER` or `NOTIFY_SENDER` left outside of ILS repos. If you want I can make PRs, but since I am not familiar I did not want to do it without asking first.

**Comment by ntarocco** [comment]
`NOTIFY_SENDER` is only in ILS, indeed. `SECURITY_EMAIL_SENDER` is part of `flask-security` and defined in RDM [invenio.cfg](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py#L245).
Given that it is there, it has to be overridden and defined in the various RDM instances.
What PRs do you want to create?

**Comment by ppanero** [comment]
@ntarocco the variable is removed from app-rdm/config.py in the [linked PR](https://github.com/inveniosoftware/invenio-app-rdm/pull/2003).

Regarding PRs:

> I think that NOTIFY_SENDER is a mistake and it should be removed.

I didnt understand if this comment of yours meant that you wanted me to make a PR to ILS.

**Comment by ntarocco** [comment]
> @ntarocco the variable is removed from app-rdm/config.py in the [linked PR](https://github.com/inveniosoftware/invenio-app-rdm/pull/2003). Since the value is duplicated, there is no need for it to be defined (and we avoid defining it in the rdm instances)
> 
> Regarding PRs:
> 
> > I think that NOTIFY_SENDER is a mistake and it should be removed.
> 
> I didnt understand if this comment of yours meant that you wanted me to make a PR to ILS.

Ah no no, I meant that it was here before your latest changes (if I am not mistaken). In ILS it is ok like this for the moment.
Then, nothing to do here :)
